"""create players table

Revision ID: 1a0729a5ea38
Revises: 
Create Date: 2021-03-31 23:34:40.425068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a0729a5ea38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
        sa.Column('uuid', postgresql.UUID(), nullable=False),
        sa.Column('date_joined', sa.DateTime(), nullable=False),
        sa.Column('username', sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
