"""create users table

Revision ID: 5a503b995cfd
Revises: 1a0729a5ea38
Create Date: 2021-04-01 18:04:26.021296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a503b995cfd'
down_revision = '1a0729a5ea38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('username', sa.String(length=40), nullable=False),
        sa.Column('password', sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
