version: '3.7'
services:
  ws:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:8000/healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s