"""create eventlog table

Revision ID: 34f9d837ebeb
Revises: 
Create Date: 2021-04-03 14:20:23.908996

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "34f9d837ebeb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eventlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_uuid", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("player_uuid", postgresql.UUID(), nullable=False),
        sa.Column("params", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_uuid", "sequence"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eventlog")
    # ### end Alembic commands ###
