version: '3.7'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:8000/healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/:/usr/src/postgres/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xo-game

volumes:
  postgres: