version: '3.7'
services:
  api-service:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:8000/healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - api-service
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xo-api
