"""create_game_table

Revision ID: 492408566602
Revises: 5a503b995cfd
Create Date: 2021-04-04 23:03:42.761266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492408566602'
down_revision = '5a503b995cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
        sa.Column('uuid', postgresql.UUID(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('player_created', postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['player_created'], ['player.uuid'], ),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.create_foreign_key('player_username_user_username_fk', 'player', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_username_user_username_fk', 'player', type_='foreignkey')
    op.drop_table('game')
    # ### end Alembic commands ###
